// Dictionnaires FR / EN. Organisés par écran (même nom que le fichier
// correspondant dans app/ ou components/) pour s'y retrouver facilement.
// Voir lib/LangueContext.js pour la fonction t() qui les exploite.

export const fr = {
  commun: {
    annuler: 'Annuler',
    erreur: 'Erreur',
    ok: 'OK',
    oui: 'Oui',
    non: 'Non',
    supprimer: 'Supprimer',
  },
  accueil: {
    sousTitre: 'Organise tes tournois sportifs',
    creerMonTournoi: 'Créer mon tournoi',
    rejoindreUnTournoi: 'Rejoindre un tournoi',
    creerUnTournoi: '+ Créer un tournoi',
    rejoindre: 'Rejoindre',
    mesTournois: 'Mes tournois',
    tournoisSuivis: 'Tournois suivis',
    voirTout: 'Voir tout ({{n}})',
    voirMoins: 'Voir moins',
    statutAujourdhui: "AUJOURD'HUI",
    statutAvenir: 'À VENIR',
    statutTermine: 'TERMINÉ',
    oublierTitre: 'Oublier ce tournoi ?',
    oublierMessage: '« {{nom}} » ne sera plus proposé dans vos tournois suivis. Vous pourrez toujours le retrouver avec son code d\'accès ou son QR code.',
    oublier: 'Oublier',
    connecteComme: 'Connecté en tant que {{nom}}',
    monProfil: 'Mon profil',
    seDeconnecter: 'Se déconnecter',
    dejaInscrit: 'Déjà inscrit ? Se connecter',
  },
  connexion: {
    titre: 'Connexion',
    sousTitre: 'Accède à tes tournois',
    email: 'Adresse e-mail',
    motDePasse: 'Mot de passe',
    seConnecter: 'Se connecter',
    connexionEnCours: 'Connexion…',
    motDePasseOublie: 'Mot de passe oublié ?',
    pasEncoreDeCompte: 'Pas encore de compte ? Créer un compte',
    champsManquantsTitre: 'Champs manquants',
    champsManquantsMessage: 'Merci de renseigner ton email et ton mot de passe.',
    connexionImpossible: 'Connexion impossible',
    enregistrerIdentifiantsTitre: 'Enregistrer tes identifiants ?',
    enregistrerIdentifiantsMessage: 'Tu pourras te reconnecter en un instant si jamais tu es déconnecté. Ils restent stockés uniquement sur cet appareil, de façon chiffrée.',
    nonMerci: 'Non merci',
    enregistrer: 'Enregistrer',
  },
  inscription: {
    titre: 'Créer mon compte',
    sousTitre: 'Nécessaire pour créer et gérer tes tournois',
    nom: 'Nom',
    prenom: 'Prénom',
    club: 'Club (optionnel)',
    email: 'Adresse e-mail',
    motDePasse: 'Mot de passe',
    ajouterUnePhoto: 'Ajouter une photo',
    creerMonCompte: 'Créer mon compte',
    creationEnCours: 'Création…',
    dejaInscrit: 'Déjà inscrit ? Se connecter',
    champsManquantsTitre: 'Champs manquants',
    champsManquantsMessage: 'Merci de renseigner au minimum le nom, le prénom, l\'email et le mot de passe.',
    compteCreeTitre: 'Compte créé',
    verifieTaBoiteMailAvecPhoto: 'Vérifie ta boîte mail pour confirmer ton adresse, puis connecte-toi. Tu pourras ajouter ta photo depuis ton profil une fois connecté.',
    verifieTaBoiteMail: 'Vérifie ta boîte mail pour confirmer ton adresse, puis connecte-toi.',
  },
  motDePasseOublie: {
    titre: 'Mot de passe oublié',
    sousTitre: 'Indique ton adresse e-mail, tu recevras un lien pour choisir un nouveau mot de passe.',
    email: 'Adresse e-mail',
    adresseInvalideTitre: 'Adresse invalide',
    adresseInvalideMessage: 'Merci de renseigner ton adresse e-mail.',
    envoyerLeLien: 'Envoyer le lien',
    envoiEnCours: 'Envoi…',
    verifieTaBoiteMailTitre: 'Vérifie ta boîte mail',
    verifieTaBoiteMailMessage: 'Si un compte existe pour {{email}}, un lien de réinitialisation vient de lui être envoyé.',
    retourALaConnexion: 'Retour à la connexion',
  },
  reinitialiserMotDePasse: {
    titre: 'Nouveau mot de passe',
    sousTitre: 'Choisis un nouveau mot de passe pour ton compte.',
    nouveauMotDePasse: 'Nouveau mot de passe',
    confirmerLeMotDePasse: 'Confirmer le mot de passe',
    valider: 'Valider',
    enregistrementEnCours: 'Enregistrement…',
    lienInvalideTitre: 'Lien invalide',
    lienInvalideMessage: 'Ce lien de réinitialisation n\'est plus valide. Refais une demande depuis l\'écran de connexion.',
    lienExpireTitre: 'Lien expiré',
    lienExpireMessage: 'Ce lien de réinitialisation a expiré ou a déjà été utilisé. Refais une demande.',
    motDePasseTropCourtTitre: 'Mot de passe trop court',
    motDePasseTropCourtMessage: 'Le mot de passe doit contenir au moins 6 caractères.',
    motsDePasseDifferentsTitre: 'Les mots de passe ne correspondent pas',
    motsDePasseDifferentsMessage: 'Merci de vérifier la confirmation.',
    motDePasseModifieTitre: 'Mot de passe modifié',
    motDePasseModifieMessage: 'Tu peux maintenant utiliser ton nouveau mot de passe.',
  },
  rejoindre: {
    titre: 'Rejoindre un tournoi',
    sousTitre: 'Scanne le QR code du tournoi, ou saisis le code d\'accès communiqué par l\'organisateur',
    qrCodeDetecte: 'QR code détecté…',
    autoriseCameraReglages: 'Autorise l\'accès à la caméra dans les réglages de ton téléphone pour scanner un QR code.',
    autoriseCamera: 'Autorise l\'accès à la caméra pour scanner un QR code.',
    autoriserLaCamera: 'Autoriser la caméra',
    ou: 'ou',
    placeholderCode: 'ex : a3f9k2',
    accederAuTournoi: 'Accéder au tournoi',
    qrCodeNonReconnuTitre: 'QR code non reconnu',
    qrCodeNonReconnuMessage: 'Ce QR code ne correspond pas à un tournoi OLYMPIAD.',
  },
  choisirSport: {
    eyebrow: 'Nouveau tournoi',
    titre: 'Quel sport ?',
  },
  sports: {
    football: {
      label: 'Football', libelleDiffScore: 'Différence de buts', abregeScorePour: 'BP', abregeScoreContre: 'BC',
    },
    rugby: {
      label: 'Rugby', libelleDiffScore: 'Différence de points', abregeScorePour: 'PP', abregeScoreContre: 'PC',
    },
  },
  creerTournoi: {
    nomDuTournoi: 'Nom du tournoi',
    placeholderNom: 'Tournoi de fin d\'année',
    date: 'Date',
    choisirLaDate: 'Choisir la date du tournoi',
    format: 'Format',
    formatMixte: 'Poules puis élimination directe',
    formatPoules: 'Poules uniquement',
    formatElimination: 'Élimination directe uniquement',
    reglagesAvances: 'Réglages avancés',
    aideAvance: 'Départage des égalités — valeurs par défaut déjà sélectionnées',
    departagePoule: 'Départage · égalité en poule',
    confrontationDirecte: 'Confrontation directe',
    departageElimination: 'Départage · match nul en élimination directe',
    prolongationsTab: 'Prolongations puis tirs au but',
    tabDirect: 'Tirs au but directs',
    prolongation: 'Prolongation',
    mortSubite: 'Mort subite',
    dropGoal: 'Drop goal',
    suivant: 'Suivant',
    champsManquantsTitre: 'Champs manquants',
    champsManquantsMessage: 'Merci de renseigner le nom et la date du tournoi.',
  },
  notFound: {
    titre: 'Page introuvable',
    sousTitre: 'Ce lien ou ce code ne correspond à aucun tournoi. Vérifie le QR code ou le code d\'accès.',
    retourAlAccueil: 'Retour à l\'accueil',
  },
  profil: {
    titre: 'Mon profil',
    toucheLaPhoto: 'Touche la photo pour la changer',
    ajouterUnePhoto: 'Ajouter une photo',
    nom: 'Nom',
    prenom: 'Prénom',
    club: 'Club (optionnel)',
    enregistrer: 'Enregistrer',
    enregistrementEnCours: 'Enregistrement…',
    apparence: 'Apparence',
    apparenceAide: 'Choisis l\'affichage clair ou sombre de l\'app.',
    langue: 'Langue',
    langueAide: 'Choisis la langue de l\'app.',
    identifiantsEnregistres: 'Identifiants enregistrés',
    identifiantsEnregistresAide: 'Ton email et ton mot de passe sont enregistrés de façon chiffrée sur cet appareil pour te reconnecter rapidement.',
    oublierIdentifiants: 'Oublier les identifiants enregistrés',
    oublierIdentifiantsTitre: 'Oublier tes identifiants enregistrés ?',
    oublierIdentifiantsMessage: 'Tu devras ressaisir ton email et ton mot de passe à ta prochaine connexion sur cet appareil.',
    adresseEmail: 'Adresse e-mail',
    actuelle: 'Actuelle : {{email}}',
    placeholderNouvelEmail: 'Nouvelle adresse e-mail',
    changerAdresseEmail: 'Changer l\'adresse e-mail',
    envoiEnCours: 'Envoi…',
    motDePasse: 'Mot de passe',
    motDePasseOublie: 'Mot de passe oublié ?',
    motDePasseActuel: 'Mot de passe actuel',
    nouveauMotDePasse: 'Nouveau mot de passe',
    confirmerLeNouveauMotDePasse: 'Confirmer le nouveau mot de passe',
    changerLeMotDePasse: 'Changer le mot de passe',
    modificationEnCours: 'Modification…',
    champsManquantsTitre: 'Champs manquants',
    champsManquantsMessage: 'Le nom et le prénom sont obligatoires.',
    adresseInvalideTitre: 'Adresse invalide',
    adresseInvalideMessage: 'Merci de renseigner une adresse e-mail valide.',
    verifieTaBoiteMailTitre: 'Vérifie ta boîte mail',
    verifieTaBoiteMailMessage: 'Un e-mail de confirmation a été envoyé à {{email}}. Ta nouvelle adresse ne sera active qu\'une fois le lien confirmé.',
    motDePasseActuelManquantTitre: 'Mot de passe actuel manquant',
    motDePasseActuelManquantMessage: 'Merci de saisir ton mot de passe actuel.',
    motDePasseTropCourtTitre: 'Mot de passe trop court',
    motDePasseTropCourtMessage: 'Le mot de passe doit contenir au moins 6 caractères.',
    motsDePasseDifferentsTitre: 'Les mots de passe ne correspondent pas',
    motsDePasseDifferentsMessage: 'Merci de vérifier la confirmation.',
    motDePasseActuelIncorrectTitre: 'Mot de passe actuel incorrect',
    motDePasseActuelIncorrectMessage: 'Vérifie ton mot de passe actuel et réessaie.',
    motDePasseModifie: 'Mot de passe modifié',
    migrationNonAppliquee: 'La mise à jour n\'a pas été enregistrée (vérifie que la migration SQL a bien été exécutée sur Supabase).',
  },
  boutonRetour: {
    retour: 'Retour',
  },
  classementPoule: {
    equipe: 'Équipe',
    j: 'J',
    v: 'V',
    n: 'N',
    d: 'D',
    bp: 'BP',
    bc: 'BC',
    diff: 'Diff',
    pts: 'Pts',
    aucuneEquipe: 'Aucune équipe pour l\'instant.',
  },
  qrcode: {
    sousTitre: 'Fais scanner ce QR code aux équipes et spectateurs pour qu\'ils accèdent directement au suivi du tournoi.',
    ouAvecLeCode: 'Ou avec le code d\'accès',
    copie: 'Copié !',
    copier: 'Copier',
    partagerLeLien: 'Partager le lien',
    messagePartage: 'Suis le tournoi "{{nom}}" sur OLYMPIAD !\nCode d\'accès : {{code}}\n{{lien}}',
  },
  saisie: {
    terrain: 'terrain {{n}}',
    mene: 'MÈNE',
    egaliteTirs: 'Égalité — score des tirs au but',
    pointsBonus: 'Points bonus',
    validerLeResultat: 'Valider le résultat',
    validationEnCours: 'Validation…',
    supprimerLeResultat: 'Supprimer le résultat',
    note: 'Classement et calendrier mis à jour instantanément pour tous les participants.',
    matchEliminationTitre: 'Match à élimination directe',
    matchEliminationMessage: 'En cas d\'égalité, indique un score de tirs au but différent pour désigner le vainqueur.',
    supprimerTitre: 'Supprimer le résultat ?',
    supprimerMessage: 'Le match redeviendra "à venir".',
    resultatEnregistre: 'Résultat enregistré',
    resultatSupprime: 'Résultat supprimé',
  },
  suivi: {
    supprimerTournoiTitre: 'Supprimer ce tournoi ?',
    supprimerTournoiMessage: '« {{nom}} » ne sera plus proposé dans vos tournois suivis. Vous pourrez toujours le retrouver avec son code d\'accès ou son QR code.',
    tournoiIntrouvable: 'Tournoi introuvable',
    tournoiIntrouvableMessage: 'Ce code d\'accès ne correspond à aucun tournoi. Vérifie le code ou le QR code utilisé.',
    reessayer: 'Réessayer',
    quelleEquipe: 'Vous faites partie de quelle équipe ?',
    ou: 'ou',
    jeFaisPartieDuPublic: 'Je fais partie du public',
    tirerPourActualiser: '↓ Tirer pour actualiser',
    monEquipe: 'Mon équipe : {{nom}}',
    vueSpectateur: 'Vue spectateur',
    changer: 'Changer',
    apercu: 'Aperçu',
    calendrierOnglet: 'Calendrier',
    dernierResultat: 'Dernier résultat de votre équipe',
    prochainMatch: 'Votre prochain match',
    resultatsMonEquipe: 'Résultats de mon équipe',
    aucunResultat: 'Aucun résultat pour l\'instant.',
    matchsAVenirMonEquipe: 'Matchs à venir de mon équipe',
    aucunMatchAVenir: 'Aucun match à venir pour l\'instant.',
    tousLesResultats: 'Tous les résultats',
    matchsAVenir: 'Matchs à venir',
    aucunClassement: 'Aucun classement pour l\'instant.',
    classementPoule: 'Classement · {{nom}}',
    supprimerCeTournoi: 'Supprimer ce tournoi',
  },
  calendrier: {
    pasAssezQualifiesTitre: 'Pas assez de qualifiés',
    pasAssezQualifiesMessage: 'Il faut au moins 2 équipes qualifiées pour générer la phase finale.',
    toucheUnMatch: 'Touche un match pour saisir ou modifier son résultat',
    parPoule: 'Par poule',
    parTerrain: 'Par terrain',
    aucunMatch: 'Aucun match généré pour l\'instant.',
    exempt: 'Exempt · qualifié·e directement',
    aVenir: 'À venir',
    scoreTab: '(tab {{a}}-{{b}})',
    podium: 'Podium',
    vainqueur: '🏆 Vainqueur : {{nom}}',
    generationEnCours: 'Génération…',
    genererLaPhaseFinale: 'Générer la phase finale',
    genererFinaleEtTroisieme: 'Générer la finale et le match pour la 3e place',
    genererLeTourSuivant: 'Générer le tour suivant',
    classement: 'Classement',
    modifierMonTournoi: 'Modifier mon tournoi',
  },
  equipes: {
    retirerEquipeTitre: 'Retirer cette équipe ?',
    retirerEquipeMessage: '"{{nom}}" a déjà des matchs dans le calendrier : ils seront supprimés, avec leurs résultats éventuels.',
    retirer: 'Retirer',
    pasAssezEquipesTitre: 'Pas assez d\'équipes',
    pasAssezEquipesMessage: 'Ajoute au moins 2 équipes avant de régénérer le calendrier.',
    regenererTitre: 'Régénérer le calendrier ?',
    regenererMessage: 'Les matchs et résultats déjà saisis seront supprimés et remplacés par un nouveau calendrier.',
    regenerer: 'Régénérer',
    supprimerTournoiTitre: 'Supprimer ce tournoi ?',
    supprimerTournoiMessage: 'Cette action est définitive : équipes, matchs et résultats seront supprimés.',
    champsManquantsTitre: 'Champs manquants',
    champsManquantsMessage: 'Le nom et la date du tournoi sont obligatoires.',
    aucuneEquipeTitre: 'Aucune équipe',
    aucuneEquipeMessage: 'Ajoute au moins une équipe avant de créer le tournoi.',
    fermer: 'Fermer',
    modifierNomEtDate: 'Modifier le nom et la date',
    nomDuTournoi: 'Nom du tournoi',
    date: 'Date',
    equipesCompteur: 'Équipes · {{n}}',
    placeholderNomEquipe: 'Nom de l\'équipe',
    aucuneEquipeAjoutee: 'Aucune équipe ajoutée pour l\'instant.',
    terrainsDisponibles: 'Terrains disponibles',
    terrainsAide: 'Plusieurs matchs pourront se jouer en même temps.',
    nombreDePoules: 'Nombre de poules',
    qualifiesParPoule: 'Qualifiés par poule pour la phase finale',
    qualifiesParPouleAide: 'Nombre d\'équipes de chaque poule qui accèdent à la phase à élimination directe.',
    matchTroisiemePlace: 'Match pour la 3e place',
    matchTroisiemePlaceAide: 'Ajoute un match de classement entre les deux équipes battues en demi-finale.',
    pointsBonus: 'Points bonus',
    pointsBonusAide: 'Un point supplémentaire au classement pour l\'essai bonus offensif ou la défaite bonifiée, à saisir match par match.',
    reglagesAvancesHoraires: 'Réglages avancés · horaires',
    aideAvanceHoraires: 'Heure de départ, durées des matchs, pauses — valeurs déjà réglées',
    heurePremierMatch: 'Heure du premier match',
    dureeMatch: 'Durée d\'un match (minutes)',
    miTemps: 'Mi-temps',
    dureeMiTemps: 'Durée de la mi-temps (minutes)',
    pauseEntreMatchs: 'Pause entre chaque match (minutes)',
    pauseDejeuner: 'Pause déjeuner',
    de: 'De',
    a: 'À',
    creationEnCours: 'Création…',
    creerLeTournoi: 'Créer le tournoi',
    sauvegardeEnCours: 'Sauvegarde…',
    sauvegarder: 'Sauvegarder',
    regenererLeCalendrier: 'Régénérer le calendrier',
    avertissementRegenerer: 'Supprime et recrée les matchs à partir des réglages actuels — les résultats déjà saisis seront perdus.',
    supprimerCeTournoi: 'Supprimer ce tournoi',
  },
  selecteurDate: {
    placeholder: 'Choisir une date',
    mois: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    jours: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
  },
};

export const en = {
  commun: {
    annuler: 'Cancel',
    erreur: 'Error',
    ok: 'OK',
    oui: 'Yes',
    non: 'No',
    supprimer: 'Delete',
  },
  accueil: {
    sousTitre: 'Organize your sports tournaments',
    creerMonTournoi: 'Create my tournament',
    rejoindreUnTournoi: 'Join a tournament',
    creerUnTournoi: '+ Create a tournament',
    rejoindre: 'Join',
    mesTournois: 'My tournaments',
    tournoisSuivis: 'Followed tournaments',
    voirTout: 'See all ({{n}})',
    voirMoins: 'See less',
    statutAujourdhui: 'TODAY',
    statutAvenir: 'UPCOMING',
    statutTermine: 'FINISHED',
    oublierTitre: 'Forget this tournament?',
    oublierMessage: '"{{nom}}" will no longer appear in your followed tournaments. You can always find it again with its access code or QR code.',
    oublier: 'Forget',
    connecteComme: 'Signed in as {{nom}}',
    monProfil: 'My profile',
    seDeconnecter: 'Sign out',
    dejaInscrit: 'Already have an account? Sign in',
  },
  connexion: {
    titre: 'Sign in',
    sousTitre: 'Access your tournaments',
    email: 'Email address',
    motDePasse: 'Password',
    seConnecter: 'Sign in',
    connexionEnCours: 'Signing in…',
    motDePasseOublie: 'Forgot your password?',
    pasEncoreDeCompte: 'Don\'t have an account yet? Create one',
    champsManquantsTitre: 'Missing fields',
    champsManquantsMessage: 'Please enter your email and password.',
    connexionImpossible: 'Sign-in failed',
    enregistrerIdentifiantsTitre: 'Save your credentials?',
    enregistrerIdentifiantsMessage: 'You\'ll be able to sign back in instantly if you get signed out. They\'re stored encrypted on this device only.',
    nonMerci: 'No thanks',
    enregistrer: 'Save',
  },
  inscription: {
    titre: 'Create my account',
    sousTitre: 'Needed to create and manage your tournaments',
    nom: 'Last name',
    prenom: 'First name',
    club: 'Club (optional)',
    email: 'Email address',
    motDePasse: 'Password',
    ajouterUnePhoto: 'Add a photo',
    creerMonCompte: 'Create my account',
    creationEnCours: 'Creating…',
    dejaInscrit: 'Already have an account? Sign in',
    champsManquantsTitre: 'Missing fields',
    champsManquantsMessage: 'Please enter at least your last name, first name, email, and password.',
    compteCreeTitre: 'Account created',
    verifieTaBoiteMailAvecPhoto: 'Check your inbox to confirm your address, then sign in. You can add your photo from your profile once signed in.',
    verifieTaBoiteMail: 'Check your inbox to confirm your address, then sign in.',
  },
  motDePasseOublie: {
    titre: 'Forgot password',
    sousTitre: 'Enter your email address, you\'ll receive a link to choose a new password.',
    email: 'Email address',
    adresseInvalideTitre: 'Invalid address',
    adresseInvalideMessage: 'Please enter your email address.',
    envoyerLeLien: 'Send the link',
    envoiEnCours: 'Sending…',
    verifieTaBoiteMailTitre: 'Check your inbox',
    verifieTaBoiteMailMessage: 'If an account exists for {{email}}, a reset link has just been sent to it.',
    retourALaConnexion: 'Back to sign in',
  },
  reinitialiserMotDePasse: {
    titre: 'New password',
    sousTitre: 'Choose a new password for your account.',
    nouveauMotDePasse: 'New password',
    confirmerLeMotDePasse: 'Confirm password',
    valider: 'Confirm',
    enregistrementEnCours: 'Saving…',
    lienInvalideTitre: 'Invalid link',
    lienInvalideMessage: 'This reset link is no longer valid. Request a new one from the sign-in screen.',
    lienExpireTitre: 'Link expired',
    lienExpireMessage: 'This reset link has expired or has already been used. Request a new one.',
    motDePasseTropCourtTitre: 'Password too short',
    motDePasseTropCourtMessage: 'The password must be at least 6 characters long.',
    motsDePasseDifferentsTitre: 'Passwords don\'t match',
    motsDePasseDifferentsMessage: 'Please check the confirmation.',
    motDePasseModifieTitre: 'Password changed',
    motDePasseModifieMessage: 'You can now use your new password.',
  },
  rejoindre: {
    titre: 'Join a tournament',
    sousTitre: 'Scan the tournament\'s QR code, or enter the access code given by the organizer',
    qrCodeDetecte: 'QR code detected…',
    autoriseCameraReglages: 'Allow camera access in your phone settings to scan a QR code.',
    autoriseCamera: 'Allow camera access to scan a QR code.',
    autoriserLaCamera: 'Allow camera',
    ou: 'or',
    placeholderCode: 'e.g. a3f9k2',
    accederAuTournoi: 'Go to tournament',
    qrCodeNonReconnuTitre: 'QR code not recognized',
    qrCodeNonReconnuMessage: 'This QR code does not match an OLYMPIAD tournament.',
  },
  choisirSport: {
    eyebrow: 'New tournament',
    titre: 'Which sport?',
  },
  sports: {
    football: {
      label: 'Football', libelleDiffScore: 'Goal difference', abregeScorePour: 'GF', abregeScoreContre: 'GA',
    },
    rugby: {
      label: 'Rugby', libelleDiffScore: 'Point difference', abregeScorePour: 'PF', abregeScoreContre: 'PA',
    },
  },
  creerTournoi: {
    nomDuTournoi: 'Tournament name',
    placeholderNom: 'End of year tournament',
    date: 'Date',
    choisirLaDate: 'Choose the tournament\'s date',
    format: 'Format',
    formatMixte: 'Groups then knockout',
    formatPoules: 'Groups only',
    formatElimination: 'Knockout only',
    reglagesAvances: 'Advanced settings',
    aideAvance: 'Tiebreakers — default values already selected',
    departagePoule: 'Tiebreaker · tie in group',
    confrontationDirecte: 'Head-to-head',
    departageElimination: 'Tiebreaker · draw in knockout stage',
    prolongationsTab: 'Extra time then penalty shootout',
    tabDirect: 'Direct penalty shootout',
    prolongation: 'Extra time',
    mortSubite: 'Sudden death',
    dropGoal: 'Drop goal',
    suivant: 'Next',
    champsManquantsTitre: 'Missing fields',
    champsManquantsMessage: 'Please enter the tournament name and date.',
  },
  notFound: {
    titre: 'Page not found',
    sousTitre: 'This link or code does not match any tournament. Check the QR code or access code.',
    retourAlAccueil: 'Back to home',
  },
  profil: {
    titre: 'My profile',
    toucheLaPhoto: 'Tap the photo to change it',
    ajouterUnePhoto: 'Add a photo',
    nom: 'Last name',
    prenom: 'First name',
    club: 'Club (optional)',
    enregistrer: 'Save',
    enregistrementEnCours: 'Saving…',
    apparence: 'Appearance',
    apparenceAide: 'Choose the app\'s light or dark display.',
    langue: 'Language',
    langueAide: 'Choose the app\'s language.',
    identifiantsEnregistres: 'Saved credentials',
    identifiantsEnregistresAide: 'Your email and password are stored encrypted on this device to sign you back in quickly.',
    oublierIdentifiants: 'Forget saved credentials',
    oublierIdentifiantsTitre: 'Forget your saved credentials?',
    oublierIdentifiantsMessage: 'You\'ll need to re-enter your email and password next time you sign in on this device.',
    adresseEmail: 'Email address',
    actuelle: 'Current: {{email}}',
    placeholderNouvelEmail: 'New email address',
    changerAdresseEmail: 'Change email address',
    envoiEnCours: 'Sending…',
    motDePasse: 'Password',
    motDePasseOublie: 'Forgot your password?',
    motDePasseActuel: 'Current password',
    nouveauMotDePasse: 'New password',
    confirmerLeNouveauMotDePasse: 'Confirm new password',
    changerLeMotDePasse: 'Change password',
    modificationEnCours: 'Updating…',
    champsManquantsTitre: 'Missing fields',
    champsManquantsMessage: 'Last name and first name are required.',
    adresseInvalideTitre: 'Invalid address',
    adresseInvalideMessage: 'Please enter a valid email address.',
    verifieTaBoiteMailTitre: 'Check your inbox',
    verifieTaBoiteMailMessage: 'A confirmation email has been sent to {{email}}. Your new address will only be active once the link is confirmed.',
    motDePasseActuelManquantTitre: 'Current password missing',
    motDePasseActuelManquantMessage: 'Please enter your current password.',
    motDePasseTropCourtTitre: 'Password too short',
    motDePasseTropCourtMessage: 'The password must be at least 6 characters long.',
    motsDePasseDifferentsTitre: 'Passwords don\'t match',
    motsDePasseDifferentsMessage: 'Please check the confirmation.',
    motDePasseActuelIncorrectTitre: 'Current password incorrect',
    motDePasseActuelIncorrectMessage: 'Check your current password and try again.',
    motDePasseModifie: 'Password changed',
    migrationNonAppliquee: 'The update was not saved (check that the SQL migration has been run on Supabase).',
  },
  boutonRetour: {
    retour: 'Back',
  },
  classementPoule: {
    equipe: 'Team',
    j: 'P',
    v: 'W',
    n: 'D',
    d: 'L',
    bp: 'GF',
    bc: 'GA',
    diff: 'GD',
    pts: 'Pts',
    aucuneEquipe: 'No team yet.',
  },
  qrcode: {
    sousTitre: 'Have teams and spectators scan this QR code so they can go straight to the tournament tracker.',
    ouAvecLeCode: 'Or with the access code',
    copie: 'Copied!',
    copier: 'Copy',
    partagerLeLien: 'Share the link',
    messagePartage: 'Follow the "{{nom}}" tournament on OLYMPIAD!\nAccess code: {{code}}\n{{lien}}',
  },
  saisie: {
    terrain: 'field {{n}}',
    mene: 'LEADS',
    egaliteTirs: 'Tied — penalty shootout score',
    pointsBonus: 'Bonus points',
    validerLeResultat: 'Confirm result',
    validationEnCours: 'Confirming…',
    supprimerLeResultat: 'Delete result',
    note: 'Standings and schedule update instantly for everyone.',
    matchEliminationTitre: 'Knockout match',
    matchEliminationMessage: 'In case of a tie, enter a different penalty shootout score to determine the winner.',
    supprimerTitre: 'Delete the result?',
    supprimerMessage: 'The match will go back to "upcoming".',
    resultatEnregistre: 'Result saved',
    resultatSupprime: 'Result deleted',
  },
  suivi: {
    supprimerTournoiTitre: 'Delete this tournament?',
    supprimerTournoiMessage: '"{{nom}}" will no longer appear in your followed tournaments. You can always find it again with its access code or QR code.',
    tournoiIntrouvable: 'Tournament not found',
    tournoiIntrouvableMessage: 'This access code does not match any tournament. Check the code or QR code used.',
    reessayer: 'Try again',
    quelleEquipe: 'Which team are you with?',
    ou: 'or',
    jeFaisPartieDuPublic: 'I\'m a spectator',
    tirerPourActualiser: '↓ Pull to refresh',
    monEquipe: 'My team: {{nom}}',
    vueSpectateur: 'Spectator view',
    changer: 'Change',
    apercu: 'Overview',
    calendrierOnglet: 'Schedule',
    dernierResultat: 'Your team\'s latest result',
    prochainMatch: 'Your next match',
    resultatsMonEquipe: 'My team\'s results',
    aucunResultat: 'No result yet.',
    matchsAVenirMonEquipe: 'My team\'s upcoming matches',
    aucunMatchAVenir: 'No upcoming match yet.',
    tousLesResultats: 'All results',
    matchsAVenir: 'Upcoming matches',
    aucunClassement: 'No standings yet.',
    classementPoule: 'Standings · {{nom}}',
    supprimerCeTournoi: 'Delete this tournament',
  },
  calendrier: {
    pasAssezQualifiesTitre: 'Not enough qualifiers',
    pasAssezQualifiesMessage: 'At least 2 qualified teams are needed to generate the final stage.',
    toucheUnMatch: 'Tap a match to enter or edit its result',
    parPoule: 'By group',
    parTerrain: 'By field',
    aucunMatch: 'No match generated yet.',
    exempt: 'Bye · directly qualified',
    aVenir: 'Upcoming',
    scoreTab: '(pens {{a}}-{{b}})',
    podium: 'Podium',
    vainqueur: '🏆 Winner: {{nom}}',
    generationEnCours: 'Generating…',
    genererLaPhaseFinale: 'Generate the final stage',
    genererFinaleEtTroisieme: 'Generate the final and the match for 3rd place',
    genererLeTourSuivant: 'Generate the next round',
    classement: 'Standings',
    modifierMonTournoi: 'Edit my tournament',
  },
  equipes: {
    retirerEquipeTitre: 'Remove this team?',
    retirerEquipeMessage: '"{{nom}}" already has matches in the schedule: they\'ll be deleted, along with any results.',
    retirer: 'Remove',
    pasAssezEquipesTitre: 'Not enough teams',
    pasAssezEquipesMessage: 'Add at least 2 teams before regenerating the schedule.',
    regenererTitre: 'Regenerate the schedule?',
    regenererMessage: 'Matches and results already entered will be deleted and replaced with a new schedule.',
    regenerer: 'Regenerate',
    supprimerTournoiTitre: 'Delete this tournament?',
    supprimerTournoiMessage: 'This is permanent: teams, matches, and results will be deleted.',
    champsManquantsTitre: 'Missing fields',
    champsManquantsMessage: 'The tournament name and date are required.',
    aucuneEquipeTitre: 'No teams',
    aucuneEquipeMessage: 'Add at least one team before creating the tournament.',
    fermer: 'Close',
    modifierNomEtDate: 'Edit name and date',
    nomDuTournoi: 'Tournament name',
    date: 'Date',
    equipesCompteur: 'Teams · {{n}}',
    placeholderNomEquipe: 'Team name',
    aucuneEquipeAjoutee: 'No team added yet.',
    terrainsDisponibles: 'Available fields',
    terrainsAide: 'Several matches will be able to be played at the same time.',
    nombreDePoules: 'Number of groups',
    qualifiesParPoule: 'Qualifiers per group for the final stage',
    qualifiesParPouleAide: 'Number of teams from each group who advance to the knockout stage.',
    matchTroisiemePlace: 'Match for 3rd place',
    matchTroisiemePlaceAide: 'Adds a placement match between the two teams beaten in the semi-finals.',
    pointsBonus: 'Bonus points',
    pointsBonusAide: 'An extra standings point for the offensive try-scoring bonus or the losing bonus, entered match by match.',
    reglagesAvancesHoraires: 'Advanced settings · schedule',
    aideAvanceHoraires: 'Start time, match durations, breaks — already set',
    heurePremierMatch: 'Time of the first match',
    dureeMatch: 'Match duration (minutes)',
    miTemps: 'Half-time',
    dureeMiTemps: 'Half-time duration (minutes)',
    pauseEntreMatchs: 'Break between matches (minutes)',
    pauseDejeuner: 'Lunch break',
    de: 'From',
    a: 'To',
    creationEnCours: 'Creating…',
    creerLeTournoi: 'Create the tournament',
    sauvegardeEnCours: 'Saving…',
    sauvegarder: 'Save',
    regenererLeCalendrier: 'Regenerate the schedule',
    avertissementRegenerer: 'Deletes and recreates matches from the current settings — results already entered will be lost.',
    supprimerCeTournoi: 'Delete this tournament',
  },
  selecteurDate: {
    placeholder: 'Choose a date',
    mois: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    jours: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  },
};
